(kern-mk-map 'm_moongate_clearing 32 32 pal_expanded
             (list
             ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. tD tt tt tt tt tt tt tt t5 tA .. .. "
             ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. tC t3 tt tt tt tt tt tt tt tt tt t5 tA .. "
             ".. .. .. .. .. .. .. .. tC t3 tt t5 tA .. .. .. .. tC t3 tt tt tt tt tt tt tt tt tt tt tt t5 tA "
             ".. .. .. .. .. .. .. tC t3 tt tt tt t5 tA .. .. .. t3 tt tt tt tt tt tt || || || tt tt tt tt t5 "
             ".. .. .. .. .. .. .. t3 tt tt tt tt tt t5 .. .. .. tt tt tt tt tt tt || || || || || tt tt tt tt "
             ".. .. .. .. .. .. .. ta tt tt tt tt tt tc .. .. .. tt tt tt tt tt tt || || || || || tt tt tt tt "
             ".. .. .. .. .. .. .. t% ta tt tt tt tc t# .. .. .. ta tt tt tt tt tt || || || || || tt tt tt tt "
             ".. .. .. .. .. .. .. .. t% ta tt tc t# .. .. .. .. t% tt tt tt tt tt || || || || || tt tt tt tt "
             ".. tC t3 tt t5 tA .. .. .. .. .. .. .. .. .. .. .. .. ta tt tt tt tt tt || || || tt tt tt tt tt "
             ".. t3 tt tt tt t5 tA .. .. .. .. .. .. .. .. .. .. .. t% ta tt tt tt tt tt tt tt tt tt tt tt tt "
             ".. tt tt tt tt tt t5 .. .. .. .. .. .. .. .. .. .. .. .. .. t% tt tt tt tt tt tt tt tt tt tt tc "
             "tC tt tt tt tt tt tt tA .. .. .. .. .. bb .. .. .. bb .. .. .. ta tt tt tt tt tt tt tt tt tc t# "
             "t3 tt tt tt tt tt tt t5 tA .. .. .. .. .. .. .. .. .. .. .. .. t% ta tt tt tt tt tt tt tc t# .. "
             "tt tt tt tt tt tt tt tt t5 .. .. bb .. .. .. .. .. .. .. bb .. .. .. .. .. t% ta tt tc t# .. .. "
             "tt tt tt tt tt tt tt tt tc .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. "
             "tt tt tt tt tt tt tt tt t# .. .. .. .. .. .. dd .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. "
             "ta tt tt tt tt tt tt tt tA .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. "
             "t% ta tt tt tt tt tt tt t5 .. .. bb .. .. .. .. .. .. .. bb .. .. .. .. .. .. .. .. .. .. .. .. "
             ".. t% ta tt tt tt tt tt tt tA .. .. .. .. .. .. .. .. .. .. .. tC t3 tt t5 tA .. .. .. tC t3 t5 "
             ".. .. t% ta tt tt tt tt tt t5 .. .. .. bb .. .. .. bb .. .. .. t3 tt tt tt t5 tA tC t3 tt tt tt "
             ".. .. .. tD tt tt tt tt tt tt tA .. .. .. .. .. .. .. .. .. tC tt tt tt tt tt tt tt tt tt tt tt "
             ".. .. tC t3 tt tt tt tt tt tt tt t5 tA .. .. .. .. .. .. t3 tt tt tt tt tt tt tt tt tt tt tt tt "
             ".. tC t3 tt tt tt tt tt tt tt tt tt t5 tA .. .. .. .. tC tt tt tt tt tt tt tt tt tt tt tt tt tt "
             "tE t3 tt tt tt || || tt tt tt tt tt tt t5 .. .. .. .. t3 tt tt tt tt tt tt tt tt tt tt tt tt tc "
             "t3 tt tt || || || || || tt tt tt tt tt tt .. .. .. .. tt tt tt tt tt tt tt tt tt tt tt tc t# t% "
             "tt tt || || || || || || || tt tt tt tt tt .. .. .. .. tt tt tt tt tt tt tt tt tc t# .. .. .. .. "
             "tt tt || || || || || || || tt tt tt tt tt .. .. .. .. tt tt tt tt tt tt tt t# .. .. .. .. .. .. "
             "tt tt || || || || || || || tt tt tt tt tt .. .. .. .. tt tt tt tt tt tt tc .. .. .. .. .. .. .. "
             "tt tt tt || || || || || tt tt tt tt tt tc .. .. .. .. ta tt tt tt tt tt t# .. .. .. .. .. .. .. "
             "ta tt tt tt tt || || tt tt tt tt tt tc t# .. .. .. .. t% ta tt tt tt tc .. .. .. .. .. .. .. .. "
             "t% ta tt tt tt tt tt tt tt tt tt t# .. .. .. .. .. .. .. t% tt tt tt t# .. .. .. .. .. .. .. .. "
             ".. t% ta tt tt tt tt tt tt tt tc .. .. .. .. .. .. .. .. .. ta tt tt tA .. .. .. .. .. .. .. .. "
             ))

